### ISSUE TITLE
Re-think the wallet name to something nicer

### ISSUE THREAD

**Issue by jackveiga** [pokettocash/poketto-ios#1]
🔥👛

**Comment by jackveiga** [comment]
We should try to get this done asap since it influences some of the design

**Comment by jackveiga** [comment]
- poketto
- scoop
- palm
- fold
- penny
- clerk
- magnet
- zip
- pouch
- little
- tiny
- bolsa

**Comment by andresousa** [comment]
I like poketto. Also like penny. Let's drop here some more and then we'll see.

**Comment by alvesjtiago** [comment]
* plain
* bare
* simp

**Comment by andresousa** [comment]
- flow
- day
- capsule

**Comment by andresousa** [comment]
- case
- folder

**Comment by andresousa** [comment]
- flat

**Comment by andresousa** [comment]
- singleton
