### ISSUE TITLE
Use automatic gas cost if available

### ISSUE THREAD

**Issue by andresousa** [pokettocash/poketto-ios#54]

**Comment by alvesjtiago** [comment]
As mention on the xDai website, the cost of a transaction is supposedly fixed to 1 Gwei. We should probably test this value and set it hard-coded on the app.

<img width="1160" alt="Screenshot 2019-05-10 at 11 32 50" src="https://user-images.githubusercontent.com/407470/57522687-ce5c2500-731a-11e9-9639-7c66df7e1927.png">

**Comment by andresousa** [comment]
Makes sense. Let's do it!

**Comment by alvesjtiago** [comment]
Gas price and limit fixed.
