### ISSUE TITLE
Ability to add a note to a transaction

### ISSUE THREAD

**Issue by alvesjtiago** [pokettocash/poketto-ios#75]
It should be possible to add a note / memo to a transaction that gets registered on chain.
With this solution it would be possible for both parties to know what the transaction refers to.

There is the problem of being public information so there could also be an option to make this info private by encrypting with the user's private key (?).

Another option would be to add a note that gets stored in the app (and eventually sync via iCloud) but then it wouldn't be accessible anywhere.

**Describe alternatives you've considered**

This feature came from discussions on Discord and here's an example of a transaction with an UTF-8 string on the transaction input.

![image0](https://user-images.githubusercontent.com/407470/58956272-d54d4a80-8795-11e9-90d3-1b36a32d1708.png)

**Comment by andresousa** [comment]
We have already implemented public notes with 55 max characters.
